<?php
/**
 * QianfanApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Baiducloud\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * 千帆SDK
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: unset
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Baiducloud\SDK\Test\Api;

use \Baiducloud\SDK\Configuration;
use \Baiducloud\SDK\ApiException;
use \Baiducloud\SDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * QianfanApiTest Class Doc Comment
 *
 * @category Class
 * @package  Baiducloud\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class QianfanApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for chat
     *
     * 调用对话类大模型.
     *
     */
    public function testChat()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for completion
     *
     * 调用续写类大模型.
     *
     */
    public function testCompletion()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for embedding
     *
     * 调用支持向量计算类的大模型接口.
     *
     */
    public function testEmbedding()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plugin
     *
     * 调用插件接口.
     *
     */
    public function testPlugin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for text2image
     *
     * 调用文生图类大模型.
     *
     */
    public function testText2image()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
